version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-node
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: yarn
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn build:prod
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist

  deploy:
    docker:
      - image: circleci/node:latest-node
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Deploy Master to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN

  workflows:
    version: 2
  
    build_deploy:
      jobs:
        - build
        - deploy:
            requires:
              - build
            filters:
              branches:
                only: master
